// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeUI.Data;

#nullable disable

namespace RecipeUI.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20251005134028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RecipeUI.Models.Alapanyag", b =>
                {
                    b.Property<int>("AlapanyagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlapanyagNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mertekegyseg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlapanyagID");

                    b.HasIndex("AlapanyagNev")
                        .IsUnique();

                    b.ToTable("Alapanyagok");
                });

            modelBuilder.Entity("RecipeUI.Models.Raktar", b =>
                {
                    b.Property<int>("AlapanyagID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Mennyiseg")
                        .HasColumnType("TEXT");

                    b.HasKey("AlapanyagID");

                    b.ToTable("Raktarak");
                });

            modelBuilder.Entity("RecipeUI.Models.Recept", b =>
                {
                    b.Property<int>("ReceptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Elkeszites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceptNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReceptID");

                    b.ToTable("Receptek");
                });

            modelBuilder.Entity("RecipeUI.Models.ReceptHozzavalo", b =>
                {
                    b.Property<int>("ReceptID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlapanyagID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SzükségesMennyiseg")
                        .HasColumnType("TEXT");

                    b.HasKey("ReceptID", "AlapanyagID");

                    b.HasIndex("AlapanyagID");

                    b.ToTable("ReceptHozzavalok");
                });

            modelBuilder.Entity("RecipeUI.Models.Raktar", b =>
                {
                    b.HasOne("RecipeUI.Models.Alapanyag", "Alapanyag")
                        .WithMany("Raktarak")
                        .HasForeignKey("AlapanyagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alapanyag");
                });

            modelBuilder.Entity("RecipeUI.Models.ReceptHozzavalo", b =>
                {
                    b.HasOne("RecipeUI.Models.Alapanyag", "Alapanyag")
                        .WithMany("ReceptHozzavalok")
                        .HasForeignKey("AlapanyagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeUI.Models.Recept", "Recept")
                        .WithMany("Hozzavalok")
                        .HasForeignKey("ReceptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alapanyag");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("RecipeUI.Models.Alapanyag", b =>
                {
                    b.Navigation("Raktarak");

                    b.Navigation("ReceptHozzavalok");
                });

            modelBuilder.Entity("RecipeUI.Models.Recept", b =>
                {
                    b.Navigation("Hozzavalok");
                });
#pragma warning restore 612, 618
        }
    }
}
